name: shop_store
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  google_sign_in: 5.2.1
  firebase_auth: 4.4.2
  firebase_core: 2.10.0
  firebase_core_platform_interface: 4.6.0
  get: 4.6.6
  get_storage: 2.0.3
  google_fonts: 2.1.0
  http: 0.13.4
  lottie: 2.3.2
  badges: 2.0.2
  smooth_page_indicator: 1.0.0+2
  carousel_slider: 4.0.0


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/

